### ISSUE TITLE
Multile exclude expressions

### ISSUE THREAD

**Issue by feddischson** [feddischson/include_gardener#2]
It would be nice for this tool to support multiple exclude definitions.

So the user could some something like 
```
include_gardener ./my_headers/ -e "_p\.h"  -e  -e "_x\.h" 
```
to exclude all `*_p.h` and all `*_x.h` files.

**Comment by vjvishjn** [comment]
Can't a single exclude expression handle all files to be excluded? 

I am talking something like this

`include_gardener ./my_headers/ -e "_p\.h"  "_x\.h" `

to exclude all *_p.h and all *_x.h files.

**Comment by feddischson** [comment]
I don't think so.

This tool is using [Boost's program pptions](http://www.boost.org/doc/libs/1_58_0/doc/html/program_options.html) for parsing the command line arguments.

The first part `-e "_p\.h"` would be parsed as one option, and the second part `_x\.h"`
would be parsed as a positional option.

Have also a look here:
http://www.boost.org/doc/libs/1_58_0/doc/html/program_options/tutorial.html#idp337627504

But it is possible to specify one option multiple times as it is used with the '-I' option.

**Comment by vjvishjn** [comment]
Okay, I got it. I will do the same and send the pull request. :)

**Comment by feddischson** [comment]
Okay, sounds good ... thx :)
