### ISSUE TITLE
Incorrect process-path argument causes application to crash

### ISSUE THREAD

**Issue by SMemsky** [feddischson/include_gardener#6]
Running
```bash
$ include_gardener --process-path source/* --exclude '.*\.o|Makefile'
```
will cause application to quit with an uncaught exception if `source` contains something but directories.

Not taking this into account, application compiles and runs great on Mac OS with CLang.
I also think that adding ability to recursively find source files in process-path and include-path would be a nice feature

**Comment by feddischson** [comment]
Thanks for finding this bug.
